# Generated by Django 3.2.4 on 2022-12-06 12:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MongoInstance",
            fields=[
                (
                    "instance_id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="实例ID"),
                ),
                ("instance_name", models.CharField(max_length=128, verbose_name="实例名称")),
                (
                    "instance_create_type",
                    models.CharField(
                        choices=[("PAGE_LOGIN", "PAGE_LOGIN"), ("SESSION_AUTH", "SESSION_AUTH")],
                        default="PAGE_LOGIN",
                        max_length=128,
                        verbose_name="实例创建类型",
                    ),
                ),
                ("db_host", models.CharField(max_length=256, verbose_name="数据库地址")),
                ("db_port", models.IntegerField(default=27017, verbose_name="数据库端口")),
                ("db_user", models.CharField(blank=True, max_length=128, null=True, verbose_name="数据库用户名")),
                ("db_password", models.CharField(blank=True, max_length=256, null=True, verbose_name="数据库密码")),
                ("auth_source", models.CharField(default="admin", max_length=128, verbose_name="认证数据库")),
                (
                    "auth_mechanism",
                    models.CharField(
                        choices=[
                            ("SCRAM-SHA-256", "SCRAM-SHA-256"),
                            ("MONGODB-X509", "MONGODB-X509"),
                            ("MONGODB-CR", "MONGODB-CR"),
                            ("PLAIN", "PLAIN"),
                            ("MONGODB-AWS", "MONGODB-AWS"),
                            ("GSSAPI", "GSSAPI"),
                            ("DEFAULT", "DEFAULT"),
                            ("SCRAM-SHA-1", "SCRAM-SHA-1"),
                        ],
                        default="DEFAULT",
                        max_length=128,
                        verbose_name="认证方式",
                    ),
                ),
                ("update_time", models.DateTimeField(auto_now_add=True)),
                ("is_show", models.BooleanField(default=False, verbose_name="实例是否显示用于登录")),
                ("dbs_user_rtx", models.CharField(max_length=128, verbose_name="dbs用户名")),
            ],
            options={
                "db_table": "mongo_instance",
                "ordering": ["-update_time"],
            },
        ),
    ]
