# Generated by Django 3.2.4 on 2022-12-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mongoinstance",
            name="update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
