# Generated by Django 3.2.4 on 2023-01-04 08:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_alter_mongoinstance_update_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="MongoInstanceSessionInfo",
            fields=[
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name="会话ID"),
                ),
                ("instance_id", models.UUIDField(verbose_name="session会话对应的实例id")),
                ("expire_at", models.DateTimeField(verbose_name="会话过期时间")),
                ("dbs_user_rtx", models.CharField(max_length=128, verbose_name="session会话生效人")),
                ("callback_url", models.URLField(blank=True, max_length=256, null=True, verbose_name="session回调审计url")),
                ("created_by", models.CharField(max_length=128, verbose_name="session会话创建人")),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
