# Generated by Django 3.2.4 on 2023-01-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_mongoinstancesessioninfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mongoinstancesessioninfo",
            options={"ordering": ["-update_time"]},
        ),
        migrations.AlterModelTable(
            name="mongoinstancesessioninfo",
            table="mongo_instance_session_info",
        ),
    ]
