# Generated by Django 3.2.4 on 2023-01-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_alter_mongoinstance_instance_create_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mongoinstance",
            name="created_by",
            field=models.CharField(default="", max_length=32, verbose_name="实例创建者"),
        ),
        migrations.AlterField(
            model_name="mongoinstance",
            name="dbs_user_rtx",
            field=models.CharField(max_length=32, verbose_name="dbs用户名"),
        ),
    ]
