# Generated by Django 3.2.4 on 2023-01-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0006_auto_20230109_2341"),
    ]

    operations = [
        migrations.AddField(
            model_name="mongoinstancesessioninfo",
            name="source_instance_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="共享的源实例id"),
        ),
    ]
