# Generated by Django 3.2.4 on 2023-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_mongoinstancesessioninfo_source_instance_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationRecord",
            fields=[
                ("trace_id", models.UUIDField(primary_key=True, serialize=False, verbose_name="请求的trace_id")),
                ("instance_id", models.UUIDField(verbose_name="mongo实例id")),
                ("api_name", models.CharField(max_length=64, verbose_name="操作的api名称")),
                ("api_data", models.JSONField(verbose_name="操作请求数据")),
                ("api_response", models.TextField(verbose_name="请求结果")),
                ("occur_time", models.DateTimeField(auto_now_add=True, verbose_name="操作发生时间")),
            ],
            options={
                "db_table": "mongo_operation_record",
                "ordering": ["-occur_time"],
            },
        ),
    ]
