# Generated by Django 3.2.4 on 2023-01-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0008_operationrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationrecord",
            name="api_data",
            field=models.TextField(verbose_name="操作请求数据"),
        ),
    ]
